version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./build/backend-dockerfile
    env_file: prod.env
    ports:
      - "127.0.0.1:23456:80"

  frontend:
    build:
      context: .
      dockerfile: ./build/frontend-dockerfile
    ports:
      - "127.0.0.1:3000:80"

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
