"""set up access tables

Revision ID: 15c638274eb8
Revises: 450bd6051482
Create Date: 2025-04-18 13:36:44.347296

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "15c638274eb8"
down_revision: Union[str, None] = "450bd6051482"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("project_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column(
            "last_updated_dt",
            mysql.TIMESTAMP(),
            server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("project_name"),
    )
    op.create_index("ix_last_updated_dt", "projects", ["last_updated_dt"], unique=False)
    op.create_index("ix_project_name", "projects", ["project_name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("iat", sa.Integer(), nullable=False),
        sa.Column(
            "last_updated_dt",
            mysql.TIMESTAMP(),
            server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "user_access",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("project_name", sa.String(length=50), nullable=False),
        sa.Column(
            "last_updated_dt",
            mysql.TIMESTAMP(),
            server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_name"], ["projects.project_name"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "project_name", name="uix_username_projectname"),
    )
    op.create_index("ix_last_updated_dt", "user_access", ["last_updated_dt"], unique=False)
    op.create_index("ix_project_name", "user_access", ["project_name"], unique=False)
    op.create_index("ix_username", "user_access", ["username"], unique=False)
    op.drop_index("ix_last_updated_dt", table_name="teams")
    op.drop_table("teams")
    op.drop_index("ix_last_updated_dt", table_name="docs")
    op.drop_index("name", table_name="doc_history")
    op.drop_index("ix_last_updated_dt", table_name="hashcheck")
    op.drop_table("hashcheck")
    op.alter_column("doc_history", "name", existing_type=mysql.VARCHAR(length=50), nullable=True)
    op.drop_index("idx_name", table_name="doc_history")
    op.drop_index("idx_version_major", table_name="doc_history")
    op.drop_index("idx_version_minor", table_name="doc_history")
    op.drop_index("idx_version_patch", table_name="doc_history")
    op.create_index("ix_name", "doc_history", ["name"], unique=False)
    op.create_index("ix_version_major", "doc_history", ["version_major"], unique=False)
    op.create_index("ix_version_minor", "doc_history", ["version_minor"], unique=False)
    op.create_index("ix_version_patch", "doc_history", ["version_patch"], unique=False)
    op.create_foreign_key(None, "doc_history", "docs", ["name"], ["name"], ondelete="SET NULL")
    op.add_column("docs", sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False))
    op.add_column(
        "docs", sa.Column("project_name", sa.String(length=50), server_default=sa.text('"Other"'), nullable=True)
    )
    op.create_index("ix_name", "docs", ["name"], unique=False)
    op.create_index("ix_project_name", "docs", ["project_name"], unique=False)
    op.create_unique_constraint(None, "docs", ["name"])
    op.create_foreign_key(None, "docs", "projects", ["project_name"], ["project_name"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "docs", sa.Column("project_team", mysql.VARCHAR(length=50), server_default=sa.text("'Other'"), nullable=False)
    )
    op.drop_constraint(None, "docs", type_="foreignkey")
    op.drop_constraint(None, "docs", type_="unique")
    op.drop_index("ix_project_name", table_name="docs")
    op.drop_index("ix_name", table_name="docs")
    op.drop_column("docs", "project_name")
    op.drop_column("docs", "id")
    op.drop_constraint(None, "doc_history", type_="foreignkey")
    op.drop_index("ix_version_patch", table_name="doc_history")
    op.drop_index("ix_version_minor", table_name="doc_history")
    op.drop_index("ix_version_major", table_name="doc_history")
    op.drop_index("ix_name", table_name="doc_history")
    op.create_index("idx_version_patch", "doc_history", ["version_patch"], unique=False)
    op.create_index("idx_version_minor", "doc_history", ["version_minor"], unique=False)
    op.create_index("idx_version_major", "doc_history", ["version_major"], unique=False)
    op.create_index("idx_name", "doc_history", ["name"], unique=False)
    op.alter_column("doc_history", "name", existing_type=mysql.VARCHAR(length=50), nullable=False)

    op.create_table(
        "hashcheck",
        sa.Column("project_team", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("hash", mysql.VARCHAR(length=100), nullable=False),
        sa.Column(
            "last_updated_dt",
            mysql.TIMESTAMP(),
            server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("project_team"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_last_updated_dt", "hashcheck", ["last_updated_dt"], unique=False)

    op.create_table(
        "teams",
        sa.Column("project_team", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("email", mysql.VARCHAR(length=50), nullable=True),
        sa.Column(
            "last_updated_dt",
            mysql.TIMESTAMP(),
            server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("project_team"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_last_updated_dt", "teams", ["last_updated_dt"], unique=False)
    op.drop_index("ix_username", table_name="user_access")
    op.drop_index("ix_project_name", table_name="user_access")
    op.drop_index("ix_last_updated_dt", table_name="user_access")
    op.drop_table("user_access")
    op.drop_table("users")
    op.drop_index("ix_project_name", table_name="projects")
    op.drop_index("ix_last_updated_dt", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
