apiVersion: apps/v1
kind: Deployment
metadata:
  name: babble
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: babble
  template:
    metadata:
      labels:
        app: babble
    spec:
      imagePullSecrets:
        - name: docker-hub-credentials-secret
      containers:
        - name: babble
          env:
            - name: BABBLE_DB_HOST
              value: "10.100.0.6"
            - name: BABBLE_DB_USER
              value: "myuser"
            - name: BABBLE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_PASSWORD
            - name: BABBLE_DB_PORT
              value: "3306"
            - name: BABBLE_DB_DBNAME
              value: "babble"
          image: docker.io/shsung/babble:1.0.4
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: babble-tmp-storage
              mountPath: /tmp
      volumes:
        - name: babble-tmp-storage
          persistentVolumeClaim:
            claimName: babble-pvc
---
# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: babble-service
  namespace: apps
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: babble
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: babble-pvc
  namespace: apps
spec:
  # storage class name must be retreived from kubectl get storageclass
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---

