apiVersion: apps/v1
kind: Deployment
metadata:
  name: babel
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: babel
  template:
    metadata:
      labels:
        app: babel
    spec:
      imagePullSecrets:
        - name: docker-hub-credentials-secret
      containers:
        - name: babel
          env:
            - name: BABEL_DB_HOST
              value: "10.100.0.6"
            - name: BABEL_DB_USER
              value: "myuser"
            - name: BABEL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_PASSWORD
            - name: BABEL_DB_PORT
              value: "3306"
            - name: BABEL_DB_DBNAME
              value: "babel"
          image: docker.io/shsung/babel:1.0.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
---
# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: babel-service
  namespace: apps
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: babel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: babel-pvc
  namespace: apps
spec:
  # storage class name must be retreived from kubectl get storageclass
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---

