"""generating team and hash tables

Revision ID: 450bd6051482
Revises: 87acbfea6ce7
Create Date: 2025-04-11 12:39:55.144462

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "450bd6051482"
down_revision: Union[str, None] = "87acbfea6ce7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hashcheck",
        sa.Column("project_team", sa.String(length=50), nullable=False),
        sa.Column("hash", sa.String(length=100), nullable=False),
        sa.Column(
            "last_updated_dt",
            mysql.TIMESTAMP(),
            server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("project_team"),
    )
    op.create_index("ix_last_updated_dt", "hashcheck", ["last_updated_dt"], unique=False)
    op.create_table(
        "teams",
        sa.Column("project_team", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column(
            "last_updated_dt",
            mysql.TIMESTAMP(),
            server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("project_team"),
    )
    op.create_index("ix_last_updated_dt", "teams", ["last_updated_dt"], unique=False)
    op.add_column("docs", sa.Column("is_visible", mysql.TINYINT(), server_default=sa.text("1"), nullable=False))
    op.drop_column("docs", "hidden")
    op.drop_column("docs", "project_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("docs", sa.Column("project_key", mysql.VARCHAR(length=50), nullable=True))
    op.add_column("docs", sa.Column("hidden", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column("docs", "is_visible")
    op.drop_index("ix_last_updated_dt", table_name="teams")
    op.drop_table("teams")
    op.drop_index("ix_last_updated_dt", table_name="hashcheck")
    op.drop_table("hashcheck")
    # ### end Alembic commands ###
