"""add primary key restrictions to docs

Revision ID: 7aacff6739d0
Revises: 15c638274eb8
Create Date: 2025-04-18 13:43:12.241114

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "7aacff6739d0"
down_revision: Union[str, None] = "15c638274eb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("docs") as batch_op:
        batch_op.drop_constraint("primary", type_="primary")
        batch_op.create_primary_key("id", ["id"])
        batch_op.alter_column("id", existing_type=sa.BigInteger, autoincrement=True, existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("docs") as batch_op:
        batch_op.drop_constraint("primary", type_="primary")
        batch_op.alter_column("id", existing_type=sa.BigInteger, autoincrement=False, existing_nullable=False)
        batch_op.create_primary_key("name", ["name"])
    # ### end Alembic commands ###
