"""add project key and team name

Revision ID: 87acbfea6ce7
Revises: eb6ffddb1a1a
Create Date: 2025-03-31 20:44:38.124492

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87acbfea6ce7"
down_revision: Union[str, None] = "eb6ffddb1a1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("docs", sa.Column("project_key", sa.String(length=50), nullable=True))
    op.add_column(
        "docs", sa.Column("project_team", sa.String(length=50), server_default=sa.text('"Other"'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("docs", "project_team")
    op.drop_column("docs", "project_key")
    # ### end Alembic commands ###
