"""added role to user table

Revision ID: e1d172d6789e
Revises: 7aacff6739d0
Create Date: 2025-04-18 22:13:16.297800

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e1d172d6789e"
down_revision: Union[str, None] = "7aacff6739d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("docs", "project_team")
    op.add_column("users", sa.Column("role", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.add_column(
        "docs", sa.Column("project_team", mysql.VARCHAR(length=50), server_default=sa.text("'Other'"), nullable=False)
    )
    # ### end Alembic commands ###
