"""set up model

Revision ID: eb6ffddb1a1a
Revises: c42fec3758d8
Create Date: 2025-03-30 17:40:12.919090

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "eb6ffddb1a1a"
down_revision: Union[str, None] = "c42fec3758d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "doc_history",
        "last_updated_dt",
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
    )
    op.alter_column("docs", "hidden", existing_type=mysql.TINYINT(display_width=1), nullable=False)
    op.alter_column(
        "docs",
        "last_updated_dt",
        existing_type=mysql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "docs",
        "last_updated_dt",
        existing_type=mysql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
    )
    op.alter_column("docs", "hidden", existing_type=mysql.TINYINT(display_width=1), nullable=True)
    op.alter_column(
        "doc_history",
        "last_updated_dt",
        existing_type=mysql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
    )
    # ### end Alembic commands ###
