name: Update Tag
run-name: ${{ github.actor }} is testing out GitHub Actions With Master Merge
on:
  push:
    branches:
      - master
jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Update Tag
        run: |
          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse HEAD)
          VERSION=$(cat VERSION)

          echo "Using version: $VERSION"

          # Create or update the tag (e.g., 'latest' or 'stable')
          git tag -f "v$VERSION"

          # Force push the tag to remote
          git push origin "v$VERSION" -f
