name: Run Tests
run-name: ${{ github.actor }} is running tests

on:
  push:
    branches:
      - "**"
      - "!master"
      - "!main"

jobs:
  Run-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Job information
        run: |
          echo "Triggered by a ${{ github.event_name }} event on a ${{ runner.os }} server."
          echo "Branch name - ${{ github.ref }}; repository - ${{ github.repository }}."

      - name: Setup Go 1.23.4
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Install dependencies
        working-directory: ./backend
        run: |
          go mod download
          echo "The ${{ github.repository }} repository go packages downnloaded; now testing."

      - name: Run tests
        run: |
          go test -C ./backend -v ./... -count=1
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
